// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -destination=interfaces_mock.go -package=server -source=interfaces.go
//

// Package server is a generated GoMock package.
package server

import (
	context "context"
	reflect "reflect"

	mcp "github.com/modelcontextprotocol/go-sdk/mcp"
	domain "github.com/n-r-w/team-mcp/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockICoordination is a mock of ICoordination interface.
type MockICoordination struct {
	ctrl     *gomock.Controller
	recorder *MockICoordinationMockRecorder
	isgomock struct{}
}

// MockICoordinationMockRecorder is the mock recorder for MockICoordination.
type MockICoordinationMockRecorder struct {
	mock *MockICoordination
}

// NewMockICoordination creates a new mock instance.
func NewMockICoordination(ctrl *gomock.Controller) *MockICoordination {
	mock := &MockICoordination{ctrl: ctrl}
	mock.recorder = &MockICoordinationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICoordination) EXPECT() *MockICoordinationMockRecorder {
	return m.recorder
}

// DeskCreate mocks base method.
func (m *MockICoordination) DeskCreate(ctx context.Context) (domain.DeskCreateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeskCreate", ctx)
	ret0, _ := ret[0].(domain.DeskCreateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeskCreate indicates an expected call of DeskCreate.
func (mr *MockICoordinationMockRecorder) DeskCreate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeskCreate", reflect.TypeOf((*MockICoordination)(nil).DeskCreate), ctx)
}

// MessageCreate mocks base method.
func (m *MockICoordination) MessageCreate(ctx context.Context, request domain.MessageCreateRequest) (domain.MessageCreateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageCreate", ctx, request)
	ret0, _ := ret[0].(domain.MessageCreateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageCreate indicates an expected call of MessageCreate.
func (mr *MockICoordinationMockRecorder) MessageCreate(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageCreate", reflect.TypeOf((*MockICoordination)(nil).MessageCreate), ctx, request)
}

// MessageGet mocks base method.
func (m *MockICoordination) MessageGet(ctx context.Context, request domain.MessageGetRequest) (domain.MessageGetResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageGet", ctx, request)
	ret0, _ := ret[0].(domain.MessageGetResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageGet indicates an expected call of MessageGet.
func (mr *MockICoordinationMockRecorder) MessageGet(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageGet", reflect.TypeOf((*MockICoordination)(nil).MessageGet), ctx, request)
}

// MessageList mocks base method.
func (m *MockICoordination) MessageList(ctx context.Context, request domain.MessageListRequest) (domain.MessageListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageList", ctx, request)
	ret0, _ := ret[0].(domain.MessageListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MessageList indicates an expected call of MessageList.
func (mr *MockICoordinationMockRecorder) MessageList(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageList", reflect.TypeOf((*MockICoordination)(nil).MessageList), ctx, request)
}

// TopicCreate mocks base method.
func (m *MockICoordination) TopicCreate(ctx context.Context, request domain.TopicCreateRequest) (domain.TopicCreateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopicCreate", ctx, request)
	ret0, _ := ret[0].(domain.TopicCreateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopicCreate indicates an expected call of TopicCreate.
func (mr *MockICoordinationMockRecorder) TopicCreate(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopicCreate", reflect.TypeOf((*MockICoordination)(nil).TopicCreate), ctx, request)
}

// TopicList mocks base method.
func (m *MockICoordination) TopicList(ctx context.Context, request domain.TopicListRequest) (domain.TopicListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopicList", ctx, request)
	ret0, _ := ret[0].(domain.TopicListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopicList indicates an expected call of TopicList.
func (mr *MockICoordinationMockRecorder) TopicList(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopicList", reflect.TypeOf((*MockICoordination)(nil).TopicList), ctx, request)
}

// MockIMCPRuntime is a mock of IMCPRuntime interface.
type MockIMCPRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockIMCPRuntimeMockRecorder
	isgomock struct{}
}

// MockIMCPRuntimeMockRecorder is the mock recorder for MockIMCPRuntime.
type MockIMCPRuntimeMockRecorder struct {
	mock *MockIMCPRuntime
}

// NewMockIMCPRuntime creates a new mock instance.
func NewMockIMCPRuntime(ctrl *gomock.Controller) *MockIMCPRuntime {
	mock := &MockIMCPRuntime{ctrl: ctrl}
	mock.recorder = &MockIMCPRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIMCPRuntime) EXPECT() *MockIMCPRuntimeMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockIMCPRuntime) Run(ctx context.Context, transport mcp.Transport) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, transport)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockIMCPRuntimeMockRecorder) Run(ctx, transport any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockIMCPRuntime)(nil).Run), ctx, transport)
}
