// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -destination=interfaces_mock.go -package=usecase -source=interfaces.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/n-r-w/team-mcp/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIBoardStore is a mock of IBoardStore interface.
type MockIBoardStore struct {
	ctrl     *gomock.Controller
	recorder *MockIBoardStoreMockRecorder
	isgomock struct{}
}

// MockIBoardStoreMockRecorder is the mock recorder for MockIBoardStore.
type MockIBoardStoreMockRecorder struct {
	mock *MockIBoardStore
}

// NewMockIBoardStore creates a new mock instance.
func NewMockIBoardStore(ctrl *gomock.Controller) *MockIBoardStore {
	mock := &MockIBoardStore{ctrl: ctrl}
	mock.recorder = &MockIBoardStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIBoardStore) EXPECT() *MockIBoardStoreMockRecorder {
	return m.recorder
}

// CollectExpiredDeskIDs mocks base method.
func (m *MockIBoardStore) CollectExpiredDeskIDs(ctx context.Context, now time.Time, ttl time.Duration) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectExpiredDeskIDs", ctx, now, ttl)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectExpiredDeskIDs indicates an expected call of CollectExpiredDeskIDs.
func (mr *MockIBoardStoreMockRecorder) CollectExpiredDeskIDs(ctx, now, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectExpiredDeskIDs", reflect.TypeOf((*MockIBoardStore)(nil).CollectExpiredDeskIDs), ctx, now, ttl)
}

// CreateDesk mocks base method.
func (m *MockIBoardStore) CreateDesk(ctx context.Context, createdAt time.Time) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDesk", ctx, createdAt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDesk indicates an expected call of CreateDesk.
func (mr *MockIBoardStoreMockRecorder) CreateDesk(ctx, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDesk", reflect.TypeOf((*MockIBoardStore)(nil).CreateDesk), ctx, createdAt)
}

// CreateMessage mocks base method.
func (m *MockIBoardStore) CreateMessage(ctx context.Context, topicID, title, normalizedTitle, payload string) (domain.MessageMeta, domain.BusinessStatus, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, topicID, title, normalizedTitle, payload)
	ret0, _ := ret[0].(domain.MessageMeta)
	ret1, _ := ret[1].(domain.BusinessStatus)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockIBoardStoreMockRecorder) CreateMessage(ctx, topicID, title, normalizedTitle, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockIBoardStore)(nil).CreateMessage), ctx, topicID, title, normalizedTitle, payload)
}

// CreateTopic mocks base method.
func (m *MockIBoardStore) CreateTopic(ctx context.Context, deskID, title string) (domain.TopicHeader, domain.BusinessStatus, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", ctx, deskID, title)
	ret0, _ := ret[0].(domain.TopicHeader)
	ret1, _ := ret[1].(domain.BusinessStatus)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockIBoardStoreMockRecorder) CreateTopic(ctx, deskID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockIBoardStore)(nil).CreateTopic), ctx, deskID, title)
}

// DeleteDesk mocks base method.
func (m *MockIBoardStore) DeleteDesk(ctx context.Context, deskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDesk", ctx, deskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDesk indicates an expected call of DeleteDesk.
func (mr *MockIBoardStoreMockRecorder) DeleteDesk(ctx, deskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDesk", reflect.TypeOf((*MockIBoardStore)(nil).DeleteDesk), ctx, deskID)
}

// GetMessage mocks base method.
func (m *MockIBoardStore) GetMessage(ctx context.Context, messageID string) (domain.MessageMeta, string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, messageID)
	ret0, _ := ret[0].(domain.MessageMeta)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockIBoardStoreMockRecorder) GetMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockIBoardStore)(nil).GetMessage), ctx, messageID)
}

// ListMessages mocks base method.
func (m *MockIBoardStore) ListMessages(ctx context.Context, topicID string) ([]domain.MessageHeader, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, topicID)
	ret0, _ := ret[0].([]domain.MessageHeader)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockIBoardStoreMockRecorder) ListMessages(ctx, topicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockIBoardStore)(nil).ListMessages), ctx, topicID)
}

// ListTopics mocks base method.
func (m *MockIBoardStore) ListTopics(ctx context.Context, deskID string) ([]domain.TopicHeader, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics", ctx, deskID)
	ret0, _ := ret[0].([]domain.TopicHeader)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockIBoardStoreMockRecorder) ListTopics(ctx, deskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockIBoardStore)(nil).ListTopics), ctx, deskID)
}
