// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -destination=interfaces_mock.go -package=usecase -source=interfaces.go
//

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/n-r-w/team-mcp/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockIRunRegistry is a mock of IRunRegistry interface.
type MockIRunRegistry struct {
	ctrl     *gomock.Controller
	recorder *MockIRunRegistryMockRecorder
	isgomock struct{}
}

// MockIRunRegistryMockRecorder is the mock recorder for MockIRunRegistry.
type MockIRunRegistryMockRecorder struct {
	mock *MockIRunRegistry
}

// NewMockIRunRegistry creates a new mock instance.
func NewMockIRunRegistry(ctrl *gomock.Controller) *MockIRunRegistry {
	mock := &MockIRunRegistry{ctrl: ctrl}
	mock.recorder = &MockIRunRegistryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRunRegistry) EXPECT() *MockIRunRegistryMockRecorder {
	return m.recorder
}

// CollectExpiredDeskIDs mocks base method.
func (m *MockIRunRegistry) CollectExpiredDeskIDs(ctx context.Context, now time.Time, ttl time.Duration) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectExpiredDeskIDs", ctx, now, ttl)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectExpiredDeskIDs indicates an expected call of CollectExpiredDeskIDs.
func (mr *MockIRunRegistryMockRecorder) CollectExpiredDeskIDs(ctx, now, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectExpiredDeskIDs", reflect.TypeOf((*MockIRunRegistry)(nil).CollectExpiredDeskIDs), ctx, now, ttl)
}

// CreateDesk mocks base method.
func (m *MockIRunRegistry) CreateDesk(ctx context.Context, createdAt time.Time) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDesk", ctx, createdAt)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDesk indicates an expected call of CreateDesk.
func (mr *MockIRunRegistryMockRecorder) CreateDesk(ctx, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDesk", reflect.TypeOf((*MockIRunRegistry)(nil).CreateDesk), ctx, createdAt)
}

// CreateMessage mocks base method.
func (m *MockIRunRegistry) CreateMessage(ctx context.Context, topicID, title, normalizedTitle string) (domain.MessageMeta, domain.BusinessStatus, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMessage", ctx, topicID, title, normalizedTitle)
	ret0, _ := ret[0].(domain.MessageMeta)
	ret1, _ := ret[1].(domain.BusinessStatus)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateMessage indicates an expected call of CreateMessage.
func (mr *MockIRunRegistryMockRecorder) CreateMessage(ctx, topicID, title, normalizedTitle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMessage", reflect.TypeOf((*MockIRunRegistry)(nil).CreateMessage), ctx, topicID, title, normalizedTitle)
}

// CreateTopic mocks base method.
func (m *MockIRunRegistry) CreateTopic(ctx context.Context, deskID, title string) (domain.TopicHeader, domain.BusinessStatus, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", ctx, deskID, title)
	ret0, _ := ret[0].(domain.TopicHeader)
	ret1, _ := ret[1].(domain.BusinessStatus)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// CreateTopic indicates an expected call of CreateTopic.
func (mr *MockIRunRegistryMockRecorder) CreateTopic(ctx, deskID, title any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockIRunRegistry)(nil).CreateTopic), ctx, deskID, title)
}

// DeleteDesk mocks base method.
func (m *MockIRunRegistry) DeleteDesk(ctx context.Context, deskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDesk", ctx, deskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDesk indicates an expected call of DeleteDesk.
func (mr *MockIRunRegistryMockRecorder) DeleteDesk(ctx, deskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDesk", reflect.TypeOf((*MockIRunRegistry)(nil).DeleteDesk), ctx, deskID)
}

// DeleteMessage mocks base method.
func (m *MockIRunRegistry) DeleteMessage(ctx context.Context, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockIRunRegistryMockRecorder) DeleteMessage(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockIRunRegistry)(nil).DeleteMessage), ctx, messageID)
}

// DeskExists mocks base method.
func (m *MockIRunRegistry) DeskExists(ctx context.Context, deskID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeskExists", ctx, deskID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeskExists indicates an expected call of DeskExists.
func (mr *MockIRunRegistryMockRecorder) DeskExists(ctx, deskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeskExists", reflect.TypeOf((*MockIRunRegistry)(nil).DeskExists), ctx, deskID)
}

// GetDeskSnapshot mocks base method.
func (m *MockIRunRegistry) GetDeskSnapshot(ctx context.Context, deskID string) (domain.DeskSnapshot, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeskSnapshot", ctx, deskID)
	ret0, _ := ret[0].(domain.DeskSnapshot)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetDeskSnapshot indicates an expected call of GetDeskSnapshot.
func (mr *MockIRunRegistryMockRecorder) GetDeskSnapshot(ctx, deskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeskSnapshot", reflect.TypeOf((*MockIRunRegistry)(nil).GetDeskSnapshot), ctx, deskID)
}

// GetMessageMeta mocks base method.
func (m *MockIRunRegistry) GetMessageMeta(ctx context.Context, messageID string) (domain.MessageMeta, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageMeta", ctx, messageID)
	ret0, _ := ret[0].(domain.MessageMeta)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMessageMeta indicates an expected call of GetMessageMeta.
func (mr *MockIRunRegistryMockRecorder) GetMessageMeta(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageMeta", reflect.TypeOf((*MockIRunRegistry)(nil).GetMessageMeta), ctx, messageID)
}

// ListDeskIDs mocks base method.
func (m *MockIRunRegistry) ListDeskIDs(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeskIDs", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeskIDs indicates an expected call of ListDeskIDs.
func (mr *MockIRunRegistryMockRecorder) ListDeskIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeskIDs", reflect.TypeOf((*MockIRunRegistry)(nil).ListDeskIDs), ctx)
}

// TopicExists mocks base method.
func (m *MockIRunRegistry) TopicExists(ctx context.Context, topicID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopicExists", ctx, topicID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopicExists indicates an expected call of TopicExists.
func (mr *MockIRunRegistryMockRecorder) TopicExists(ctx, topicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopicExists", reflect.TypeOf((*MockIRunRegistry)(nil).TopicExists), ctx, topicID)
}

// MockIDeskStore is a mock of IDeskStore interface.
type MockIDeskStore struct {
	ctrl     *gomock.Controller
	recorder *MockIDeskStoreMockRecorder
	isgomock struct{}
}

// MockIDeskStoreMockRecorder is the mock recorder for MockIDeskStore.
type MockIDeskStoreMockRecorder struct {
	mock *MockIDeskStore
}

// NewMockIDeskStore creates a new mock instance.
func NewMockIDeskStore(ctrl *gomock.Controller) *MockIDeskStore {
	mock := &MockIDeskStore{ctrl: ctrl}
	mock.recorder = &MockIDeskStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDeskStore) EXPECT() *MockIDeskStoreMockRecorder {
	return m.recorder
}

// CollectExpiredDeskIDs mocks base method.
func (m *MockIDeskStore) CollectExpiredDeskIDs(ctx context.Context, now time.Time, ttl time.Duration) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectExpiredDeskIDs", ctx, now, ttl)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CollectExpiredDeskIDs indicates an expected call of CollectExpiredDeskIDs.
func (mr *MockIDeskStoreMockRecorder) CollectExpiredDeskIDs(ctx, now, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectExpiredDeskIDs", reflect.TypeOf((*MockIDeskStore)(nil).CollectExpiredDeskIDs), ctx, now, ttl)
}

// DeleteDesk mocks base method.
func (m *MockIDeskStore) DeleteDesk(ctx context.Context, deskID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDesk", ctx, deskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDesk indicates an expected call of DeleteDesk.
func (mr *MockIDeskStoreMockRecorder) DeleteDesk(ctx, deskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDesk", reflect.TypeOf((*MockIDeskStore)(nil).DeleteDesk), ctx, deskID)
}

// DeleteMessage mocks base method.
func (m *MockIDeskStore) DeleteMessage(ctx context.Context, deskID, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMessage", ctx, deskID, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMessage indicates an expected call of DeleteMessage.
func (mr *MockIDeskStoreMockRecorder) DeleteMessage(ctx, deskID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMessage", reflect.TypeOf((*MockIDeskStore)(nil).DeleteMessage), ctx, deskID, messageID)
}

// EnsureDesk mocks base method.
func (m *MockIDeskStore) EnsureDesk(ctx context.Context, deskID string, createdAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureDesk", ctx, deskID, createdAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureDesk indicates an expected call of EnsureDesk.
func (mr *MockIDeskStoreMockRecorder) EnsureDesk(ctx, deskID, createdAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureDesk", reflect.TypeOf((*MockIDeskStore)(nil).EnsureDesk), ctx, deskID, createdAt)
}

// PersistMessage mocks base method.
func (m *MockIDeskStore) PersistMessage(ctx context.Context, deskID, messageID, payload string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistMessage", ctx, deskID, messageID, payload)
	ret0, _ := ret[0].(error)
	return ret0
}

// PersistMessage indicates an expected call of PersistMessage.
func (mr *MockIDeskStoreMockRecorder) PersistMessage(ctx, deskID, messageID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistMessage", reflect.TypeOf((*MockIDeskStore)(nil).PersistMessage), ctx, deskID, messageID, payload)
}

// ResolveMessage mocks base method.
func (m *MockIDeskStore) ResolveMessage(ctx context.Context, deskID, messageID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveMessage", ctx, deskID, messageID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveMessage indicates an expected call of ResolveMessage.
func (mr *MockIDeskStoreMockRecorder) ResolveMessage(ctx, deskID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveMessage", reflect.TypeOf((*MockIDeskStore)(nil).ResolveMessage), ctx, deskID, messageID)
}

// MockIHeaderQueue is a mock of IHeaderQueue interface.
type MockIHeaderQueue struct {
	ctrl     *gomock.Controller
	recorder *MockIHeaderQueueMockRecorder
	isgomock struct{}
}

// MockIHeaderQueueMockRecorder is the mock recorder for MockIHeaderQueue.
type MockIHeaderQueueMockRecorder struct {
	mock *MockIHeaderQueue
}

// NewMockIHeaderQueue creates a new mock instance.
func NewMockIHeaderQueue(ctrl *gomock.Controller) *MockIHeaderQueue {
	mock := &MockIHeaderQueue{ctrl: ctrl}
	mock.recorder = &MockIHeaderQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIHeaderQueue) EXPECT() *MockIHeaderQueueMockRecorder {
	return m.recorder
}

// AppendMessage mocks base method.
func (m *MockIHeaderQueue) AppendMessage(ctx context.Context, topicID string, header domain.MessageHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendMessage", ctx, topicID, header)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendMessage indicates an expected call of AppendMessage.
func (mr *MockIHeaderQueueMockRecorder) AppendMessage(ctx, topicID, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendMessage", reflect.TypeOf((*MockIHeaderQueue)(nil).AppendMessage), ctx, topicID, header)
}

// DeleteDesk mocks base method.
func (m *MockIHeaderQueue) DeleteDesk(ctx context.Context, deskID string, topicIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDesk", ctx, deskID, topicIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDesk indicates an expected call of DeleteDesk.
func (mr *MockIHeaderQueueMockRecorder) DeleteDesk(ctx, deskID, topicIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDesk", reflect.TypeOf((*MockIHeaderQueue)(nil).DeleteDesk), ctx, deskID, topicIDs)
}

// EnsureTopic mocks base method.
func (m *MockIHeaderQueue) EnsureTopic(ctx context.Context, deskID string, header domain.TopicHeader) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureTopic", ctx, deskID, header)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureTopic indicates an expected call of EnsureTopic.
func (mr *MockIHeaderQueueMockRecorder) EnsureTopic(ctx, deskID, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureTopic", reflect.TypeOf((*MockIHeaderQueue)(nil).EnsureTopic), ctx, deskID, header)
}

// ListMessages mocks base method.
func (m *MockIHeaderQueue) ListMessages(ctx context.Context, topicID string) ([]domain.MessageHeader, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessages", ctx, topicID)
	ret0, _ := ret[0].([]domain.MessageHeader)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListMessages indicates an expected call of ListMessages.
func (mr *MockIHeaderQueueMockRecorder) ListMessages(ctx, topicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessages", reflect.TypeOf((*MockIHeaderQueue)(nil).ListMessages), ctx, topicID)
}

// ListTopics mocks base method.
func (m *MockIHeaderQueue) ListTopics(ctx context.Context, deskID string) ([]domain.TopicHeader, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics", ctx, deskID)
	ret0, _ := ret[0].([]domain.TopicHeader)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTopics indicates an expected call of ListTopics.
func (mr *MockIHeaderQueueMockRecorder) ListTopics(ctx, deskID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockIHeaderQueue)(nil).ListTopics), ctx, deskID)
}

// RemoveMessage mocks base method.
func (m *MockIHeaderQueue) RemoveMessage(ctx context.Context, topicID, messageID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMessage", ctx, topicID, messageID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMessage indicates an expected call of RemoveMessage.
func (mr *MockIHeaderQueueMockRecorder) RemoveMessage(ctx, topicID, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMessage", reflect.TypeOf((*MockIHeaderQueue)(nil).RemoveMessage), ctx, topicID, messageID)
}
